### ISSUE TITLE
Fail to load the number of  Star / Fork

### ISSUE THREAD

**Issue by Yaoshicn** [ddavison/github-badges#18]
Hi !
When I created the badges like this:
`[![star this repo](http://githubbadges.com/star.svg?user=Yaoshicn&repo=awesome-music-for-programming&background=007ecg&color=bbb&style=flat)](https://github.com/Yaoshicn/awesome-music-for-programming)`
It didn't work, just like [![star this repo](http://githubbadges.com/star.svg?user=Yaoshicn&repo=awesome-music-for-programming&background=007ecg&color=bbb&style=flat)](https://github.com/Yaoshicn/awesome-music-for-programming)

**Comment by ddavison** [comment]
this may be because the [caching](https://github.com/ddavison/github-badges/blob/master/app.rb#L81) isn't working..

**Comment by ddavison** [comment]
this should be resolved.  pushed commit dd4b055a09f6e7ebc96553765c6cbc6bb0ddf1e9

**Comment by ddavison** [comment]
thanks for reporting it !! :+1:  :smile:

**Comment by Yaoshicn** [comment]
Thanks for fixing it!
