### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sinmineryt** [ddavison/github-badges#24]
When trying to access svg, internal server error

**Comment by sinmineryt** [comment]
Hm, it looks like this project is dead.

**Comment by ddavison** [comment]
> When trying to access svg, internal server error

This project runs on HerokuApp and the GitHub API, which both have their limitations (GitHub API 60 requests per hour), (HerokuApp cannot run all day)  so the dynos restart sometimes.  It's possible that is what happened.

> https://githubbadges.com/  is still up and running and the SVGs render fine, but again - it can flake out.
