### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Gonzalo-Mier** [ddavison/github-badges#26]
Badges are down

**Comment by ddavison** [comment]
Unfortunately this is due to Heroku's deviation from support of the Open Source community.

> https://blog.heroku.com/next-chapter

This application was previously using Heroku to run and now that Heroku does not support Free Dynos, this application is no longer running.

I'd recommend using https://shields.io/ .

**Comment by Gonzalo-Mier** [comment]
The badges of this repo were quite cool 😢  

Thanks for answering.
